// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd5gGbgkALQN2RNh1BMSLXNChXpEOFPtY',
    appId: '1:385414009878:web:271e920b556ae6b234d137',
    messagingSenderId: '385414009878',
    projectId: 'task-64349',
    authDomain: 'task-64349.firebaseapp.com',
    storageBucket: 'task-64349.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArNsQ-NBv0Cwhm8tbvtHGmhGB-uJh4824',
    appId: '1:385414009878:android:f33eb842d68de52f34d137',
    messagingSenderId: '385414009878',
    projectId: 'task-64349',
    storageBucket: 'task-64349.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-Bg4bfVM7Ct-NCTSn2qsI0KIEjhx8Stc',
    appId: '1:385414009878:ios:3a150d21d15df17a34d137',
    messagingSenderId: '385414009878',
    projectId: 'task-64349',
    storageBucket: 'task-64349.firebasestorage.app',
    iosBundleId: 'com.example.feedbackApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-Bg4bfVM7Ct-NCTSn2qsI0KIEjhx8Stc',
    appId: '1:385414009878:ios:3a150d21d15df17a34d137',
    messagingSenderId: '385414009878',
    projectId: 'task-64349',
    storageBucket: 'task-64349.firebasestorage.app',
    iosBundleId: 'com.example.feedbackApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd5gGbgkALQN2RNh1BMSLXNChXpEOFPtY',
    appId: '1:385414009878:web:802ed93cbb7dca7934d137',
    messagingSenderId: '385414009878',
    projectId: 'task-64349',
    authDomain: 'task-64349.firebaseapp.com',
    storageBucket: 'task-64349.firebasestorage.app',
  );

}